// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: () => typedError<string, Error>(__TAURI_INVOKE("ping")),
	connectorCapabilities: (kind: ConnectorKind) => typedError<Capability[], Error>(__TAURI_INVOKE("connector_capabilities", { kind })),
	listConnections: () => typedError<ConnectionProfile[], Error>(__TAURI_INVOKE("list_connections")),
	getConnection: (id: string) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("get_connection", { id })),
	createConnection: (input: ConnectionInput) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("create_connection", { input })),
	updateConnection: (id: string, input: ConnectionInput) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("update_connection", { id, input })),
	deleteConnection: (id: string) => typedError<null, Error>(__TAURI_INVOKE("delete_connection", { id })),
	/**  Ephemeral connect + health check; never touches the active connections. */
	testConnection: (input: ConnectionInput, existingId: string | null) => typedError<null, Error>(__TAURI_INVOKE("test_connection", { input, existingId })),
	connect: (id: string) => typedError<null, Error>(__TAURI_INVOKE("connect", { id })),
	disconnect: (id: string) => typedError<null, Error>(__TAURI_INVOKE("disconnect", { id })),
	activeConnections: () => typedError<string[], Error>(__TAURI_INVOKE("active_connections")),
	serverVersion: (id: string) => typedError<string | null, Error>(__TAURI_INVOKE("server_version", { id })),
	runQuery: (id: string, sql: string) => typedError<QueryResult, Error>(__TAURI_INVOKE("run_query", { id, sql })),
	cancelQuery: (id: string) => typedError<null, Error>(__TAURI_INVOKE("cancel_query", { id })),
	tableRows: (id: string, request: TableRowsRequest) => typedError<QueryResult, Error>(__TAURI_INVOKE("table_rows", { id, request })),
	streamTableRows: (id: string, request: TableRowsRequest, channel: Channel<RowsChunk>) => typedError<StreamSummary, Error>(__TAURI_INVOKE("stream_table_rows", { id, request, channel })),
	/**
	 *  Streams the full filtered/sorted table to a file; rows never enter the
	 *  webview. Cancel = `cancel_query` on the same connection; a canceled or
	 *  failed export removes the partial file.
	 */
	exportTableRows: (id: string, request: TableRowsRequest, format: ExportFormat, path: string, channel: Channel<ExportProgress>) => typedError<StreamSummary, Error>(__TAURI_INVOKE("export_table_rows", { id, request, format, path, channel })),
	/**  Materialized results (SQL editor); the grid path is `export_table_rows`. */
	exportStatement: (columns: QueryColumn[], rows: ((string | null)[])[], format: ExportFormat, kind: ConnectorKind, table: string, path: string) => typedError<null, Error>(__TAURI_INVOKE("export_statement", { columns, rows, format, kind, table, path })),
	/**  Clipboard copy: same formats, returned as a string. */
	formatStatement: (columns: QueryColumn[], rows: ((string | null)[])[], format: ExportFormat, kind: ConnectorKind, table: string) => typedError<string, Error>(__TAURI_INVOKE("format_statement", { columns, rows, format, kind, table })),
	applyTableChanges: (id: string, changes: TableChanges) => typedError<ApplyResult, Error>(__TAURI_INVOKE("apply_table_changes", { id, changes })),
	schemaSnapshot: (id: string) => typedError<SchemaSnapshot, Error>(__TAURI_INVOKE("schema_snapshot", { id })),
	tableDdl: (id: string, schema: string, table: string) => typedError<string, Error>(__TAURI_INVOKE("table_ddl", { id, schema, table })),
	scanKeys: (id: string, pattern: string, cursor: string | null, count: number) => typedError<KeyScanPage, Error>(__TAURI_INVOKE("scan_keys", { id, pattern, cursor, count })),
	keyDetail: (id: string, key: string) => typedError<KeyDetail, Error>(__TAURI_INVOKE("key_detail", { id, key })),
	kvSetString: (id: string, key: string, value: string) => typedError<null, Error>(__TAURI_INVOKE("kv_set_string", { id, key, value })),
	kvDeleteKey: (id: string, key: string) => typedError<null, Error>(__TAURI_INVOKE("kv_delete_key", { id, key })),
	kvSetTtl: (id: string, key: string, ttlMs: number | null) => typedError<null, Error>(__TAURI_INVOKE("kv_set_ttl", { id, key, ttlMs })),
	kvRunCommand: (id: string, command: string) => typedError<string[], Error>(__TAURI_INVOKE("kv_run_command", { id, command })),
	kvDatabases: (id: string) => typedError<KvDatabases, Error>(__TAURI_INVOKE("kv_databases", { id })),
	kvSelectDb: (id: string, db: number) => typedError<null, Error>(__TAURI_INVOKE("kv_select_db", { id, db })),
	docDatabases: (id: string) => typedError<DocDatabase[], Error>(__TAURI_INVOKE("doc_databases", { id })),
	docCollections: (id: string, db: string) => typedError<DocCollection[], Error>(__TAURI_INVOKE("doc_collections", { id, db })),
	docFind: (id: string, request: DocFindRequest) => typedError<DocPage, Error>(__TAURI_INVOKE("doc_find", { id, request })),
	docDetail: (id: string, db: string, collection: string, docId: string) => typedError<DocDetail, Error>(__TAURI_INVOKE("doc_detail", { id, db, collection, docId })),
	docReplace: (id: string, db: string, collection: string, docId: string, doc: string) => typedError<null, Error>(__TAURI_INVOKE("doc_replace", { id, db, collection, docId, doc })),
	docDelete: (id: string, db: string, collection: string, docId: string) => typedError<null, Error>(__TAURI_INVOKE("doc_delete", { id, db, collection, docId })),
	docIndexes: (id: string, db: string, collection: string) => typedError<IndexInfo[], Error>(__TAURI_INVOKE("doc_indexes", { id, db, collection })),
	docCount: (id: string, db: string, collection: string, filter: string | null) => typedError<DocCount, Error>(__TAURI_INVOKE("doc_count", { id, db, collection, filter })),
	docRunQuery: (id: string, db: string, collection: string, source: string) => typedError<DocQueryResult, Error>(__TAURI_INVOKE("doc_run_query", { id, db, collection, source })),
	openSqlSession: (connectionId: string) => typedError<string, Error>(__TAURI_INVOKE("open_sql_session", { connectionId })),
	runSessionQuery: (id: string, sql: string) => typedError<QueryResult, Error>(__TAURI_INVOKE("run_session_query", { id, sql })),
	cancelSessionQuery: (id: string) => typedError<null, Error>(__TAURI_INVOKE("cancel_session_query", { id })),
	closeSqlSession: (id: string) => typedError<null, Error>(__TAURI_INVOKE("close_sql_session", { id })),
	listTunnels: () => typedError<TunnelProfile[], Error>(__TAURI_INVOKE("list_tunnels")),
	getTunnel: (id: string) => typedError<TunnelProfile, Error>(__TAURI_INVOKE("get_tunnel", { id })),
	createTunnel: (input: TunnelInput) => typedError<TunnelProfile, Error>(__TAURI_INVOKE("create_tunnel", { input })),
	updateTunnel: (id: string, input: TunnelInput) => typedError<TunnelProfile, Error>(__TAURI_INVOKE("update_tunnel", { id, input })),
	deleteTunnel: (id: string) => typedError<null, Error>(__TAURI_INVOKE("delete_tunnel", { id })),
	/**
	 *  Ephemeral tunnel bring-up: validates the host key and the credentials
	 *  without touching a database (no channel is opened until a client connects).
	 */
	testTunnel: (input: TunnelInput, existingId: string | null) => typedError<null, Error>(__TAURI_INVOKE("test_tunnel", { input, existingId })),
	defaultSshKeys: () => typedError<string[], Error>(__TAURI_INVOKE("default_ssh_keys")),
	trustHostKey: (host: string, port: number, key: string) => typedError<null, Error>(__TAURI_INVOKE("trust_host_key", { host, port, key })),
	mcpStatus: () => typedError<McpStatus, Error>(__TAURI_INVOKE("mcp_status")),
	mcpStart: (port: number | null) => typedError<McpStatus, Error>(__TAURI_INVOKE("mcp_start", { port })),
	mcpStop: () => typedError<null, Error>(__TAURI_INVOKE("mcp_stop")),
	mcpRegenerateToken: () => typedError<McpStatus, Error>(__TAURI_INVOKE("mcp_regenerate_token")),
	mcpAuditLog: (limit: number | null) => typedError<AuditEntry[], Error>(__TAURI_INVOKE("mcp_audit_log", { limit })),
	mcpResolveApproval: (id: string, approved: boolean) => typedError<null, Error>(__TAURI_INVOKE("mcp_resolve_approval", { id, approved })),
};

/** Events */
export const events = {
	mcpApprovalRequest: makeEvent<McpApprovalRequest>("mcp-approval-request"),
};

/* Types */
/**  What the MCP server may do with a connection; `None` hides it from agents entirely. */
export type AgentAccess = "none" | "read-only" | "write-with-approval";

export type ApplyResult = {
	updated: number,
	inserted: number,
	deleted: number,
	durationMs: number | null,
};

export type AuditEntry = {
	/**  Milliseconds since the epoch; f64 because specta forbids u64 in bindings. */
	ts: number | null,
	tool: string,
	connection: string | null,
	detail: string | null,
	ok: boolean,
	error: string | null,
	durationMs: number | null,
};

export type Capability = "sql-query" | "introspection" | "kv-browse" | "doc-browse";

export type CellValue = {
	column: string,
	/**  None writes NULL. */
	value: string | null,
};

export type ColumnFilter = {
	column: string,
	op: FilterOp,
	/**  Absent for the null operators. */
	value: string | null,
};

export type ColumnInfo = {
	name: string,
	dataType: string,
	nullable: boolean,
	default: string | null,
};

/**
 *  Coarse type family for UI decisions (alignment, editors, viewers);
 *  `data_type` keeps the exact postgres name.
 */
export type ColumnKind = "bool" | "number" | "text" | "json" | "bytes" | "date-time" | "uuid" | "array" | "other";

/**  Secrets ride in on the input but are stored in the OS keychain, never in the profile. */
export type ConnectionInput = {
	name: string,
	env: Env,
	group?: string | null,
	agentAccess?: AgentAccess,
	params: ConnectorParams,
	password: string | null,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	env: Env,
	group?: string | null,
	agentAccess?: AgentAccess,
	params: ConnectorParams,
};

export type ConnectorKind = "postgres" | "mysql" | "sqlite" | "redis" | "mongo";

/**  Per-kind connection parameters; future kinds bring their own shapes. */
export type ConnectorParams = {
	kind: "postgres",
} & SqlServerParams | {
	kind: "mysql",
} & SqlServerParams | { kind: "sqlite"; path: string } | {
	kind: "redis",
} & RedisParams | {
	kind: "mongo",
} & MongoParams;

export type DocCollection = {
	name: string,
	kind: DocCollectionKind,
	/**  estimatedDocumentCount (collection metadata); None for views. */
	estimatedDocs: number | null,
	capped: boolean,
};

export type DocCollectionKind = "collection" | "view" | "timeseries" | "other";

export type DocCount = {
	count: number | null,
	/**  false when this is a metadata estimate or the exact count hit the cap. */
	exact: boolean,
};

export type DocDatabase = {
	name: string,
	/**  listDatabases sizeOnDisk; None when a restricted user forced the fallback path. */
	sizeBytes: number | null,
	empty: boolean,
};

/**
 *  Both renderings of one document: relaxed for reading, canonical for a
 *  lossless edit round-trip (relaxed collapses Int32/Int64/Double).
 */
export type DocDetail = {
	id: string | null,
	relaxed: string,
	canonical: string,
};

/**
 *  One document on the wire. `doc` is relaxed extended JSON (display); `id` is
 *  canonical extended JSON of the `_id` value alone - the lossless address for
 *  get/replace/delete (the display form must never double as the key).
 */
export type DocEntry = {
	/**  None for documents without `_id`; edit/delete are unavailable then. */
	id: string | null,
	doc: string,
};

export type DocFindRequest = {
	db: string,
	collection: string,
	/**  Extended JSON object (canonical or relaxed); None/empty = {}. */
	filter?: string | null,
	/**  Extended JSON object, e.g. {"age": -1}. */
	sort?: string | null,
	/**  Page size; clamped server-side. */
	limit: number,
	/**  Opaque continuation from the previous page; None starts over. */
	cursor?: string | null,
};

export type DocPage = {
	docs: DocEntry[],
	/**  Opaque continuation cursor; None when the iteration completed. */
	cursor: string | null,
};

export type DocQueryResult = {
	/**  Relaxed extended JSON strings; console results are read-only. */
	docs: string[],
	/**  true when results were cut at the sample cap. */
	truncated: boolean,
	durationMs: number | null,
};

export type Env = "dev" | "staging" | "prod";

/**  Normalized error shape crossing the IPC boundary. */
export type Error = { kind: "not-found"; message: string } | { kind: "storage"; message: string } | { kind: "secret"; message: string } | { kind: "unsupported"; message: string } | { kind: "database"; message: string } | { kind: "tunnel"; message: string } | { kind: "host-key-untrusted"; message: string; host: string; port: number; fingerprint: string; key: string; previouslyTrusted: boolean };

export type ExportFormat = "csv" | "json" | "sql" | "markdown";

export type ExportProgress = {
	rows: number | null,
};

export type FilterOp = "eq" | "neq" | "lt" | "lte" | "gt" | "gte" | "contains" | "starts-with" | "is-null" | "is-not-null";

export type ForeignKeyInfo = {
	name: string,
	columns: string[],
	referencedSchema: string,
	referencedTable: string,
	referencedColumns: string[],
};

export type HashField = {
	field: string,
	value: string,
};

export type IndexInfo = {
	name: string,
	definition: string,
	unique: boolean,
};

export type KeyDetail = {
	key: string,
	/**  Milliseconds to expiry; None = no expiry. */
	ttlMs: number | null,
	/**  Full collection length (bytes for strings); entries hold a bounded sample. */
	size: number | null,
	value: KeyValue,
};

export type KeyEntry = {
	key: string,
	kind: KeyKind,
	/**  Milliseconds to expiry; None = no expiry. */
	ttlMs: number | null,
};

export type KeyKind = "string" | "list" | "set" | "zset" | "hash" | "stream" | "other";

export type KeyScanPage = {
	keys: KeyEntry[],
	/**  Opaque continuation cursor; None when the iteration completed. */
	cursor: string | null,
};

export type KeyValue = { kind: "string"; value: string } | { kind: "list"; entries: string[] } | { kind: "set"; entries: string[] } | { kind: "zset"; entries: ZsetMember[] } | { kind: "hash"; entries: HashField[] } | { kind: "stream"; entries: StreamEntry[] } | { kind: "other"; typeName: string };

export type KvDatabaseKeys = {
	db: number,
	keys: number | null,
};

export type KvDatabases = {
	current: number,
	/**  Configured database count; selection targets 0..total. */
	total: number,
	/**  Non-empty databases with their key counts. */
	used: KvDatabaseKeys[],
};

/**  The MCP call stays blocked until this is answered. */
export type McpApprovalRequest = {
	id: string,
	connectionId: string,
	connectionName: string,
	sql: string,
};

export type McpStatus = {
	running: boolean,
	port: number,
	endpoint: string,
	token: string,
	serverName: string,
};

/**
 *  MongoDB single node (v1); srv/replica-set discovery later. `database` is
 *  the default db the UI opens; credentials validate against `auth_source`,
 *  falling back to `database`, then the driver's "admin" (URI semantics).
 */
export type MongoParams = {
	host: string,
	port: number,
	database?: string | null,
	username?: string | null,
	authSource?: string | null,
	tls?: boolean,
	tunnelId?: string | null,
};

export type QueryColumn = {
	name: string,
	/**  None when type metadata is unavailable (multi-statement scripts). */
	dataType: string | null,
	kind: ColumnKind,
};

export type QueryResult = {
	statements: StatementResult[],
	notices: ServerNotice[],
	durationMs: number | null,
};

/**
 *  Redis speaks AUTH, not SQL: username is optional (ACL), the database is a
 *  numeric index, and TLS is a plain toggle (rediss://).
 */
export type RedisParams = {
	host: string,
	port: number,
	db?: number,
	username?: string | null,
	tls?: boolean,
	tunnelId?: string | null,
};

export type RowDelete = {
	key: CellValue[],
};

export type RowInsert = {
	/**  Omitted columns take their DEFAULT. */
	values: CellValue[],
};

export type RowUpdate = {
	key: CellValue[],
	set: CellValue[],
};

export type RowsChunk = {
	/**  Present on the first chunk only. */
	columns: QueryColumn[] | null,
	rows: ((string | null)[])[],
};

export type SchemaInfo = {
	name: string,
	tables: TableInfo[],
};

export type SchemaSnapshot = {
	schemas: SchemaInfo[],
};

export type ServerNotice = {
	severity: string,
	message: string,
};

export type SortDirection = "asc" | "desc";

export type SortSpec = {
	column: string,
	direction: SortDirection,
};

/**  Shared shape for TCP SQL servers (postgres, mysql). */
export type SqlServerParams = {
	host: string,
	port: number,
	database: string,
	user: string,
	sslMode?: SslMode,
	/**  CA bundle path for verify-full (libpq sslrootcert); None = platform store. */
	sslRootCert?: string | null,
	tunnelId?: string | null,
};

export type SshAuth = { method: "agent" } | { method: "key-file"; path: string } | { method: "password" } | 
/**  No credential: the server authorizes the connection on its own. */
{ method: "none" };

/**
 *  libpq semantics: `require` encrypts without verifying the certificate,
 *  only `verify-full` checks the chain and hostname.
 */
export type SslMode = "disable" | "prefer" | "require" | "verify-full";

export type StatementResult = {
	columns: QueryColumn[],
	rows: ((string | null)[])[],
	rowsAffected: number | null,
};

export type StreamEntry = {
	id: string,
	fields: HashField[],
};

export type StreamSummary = {
	rows: number | null,
	durationMs: number | null,
	notices: ServerNotice[],
};

export type TableChanges = {
	schema: string,
	table: string,
	updates: RowUpdate[],
	inserts: RowInsert[],
	deletes: RowDelete[],
};

export type TableInfo = {
	name: string,
	kind: TableKind,
	/**  Planner estimate (pg reltuples): -1 when never analyzed. */
	estimatedRows: number | null,
	columns: ColumnInfo[],
	primaryKey: string[],
	indexes: IndexInfo[],
	foreignKeys: ForeignKeyInfo[],
};

export type TableKind = "table" | "view" | "materialized-view";

export type TableRowsRequest = {
	schema: string,
	table: string,
	/**  None streams the full result set (export). */
	limit: number | null,
	offset: number,
	sort: SortSpec | null,
	filters?: ColumnFilter[],
	/**  ctid-keyed editing for tables without a primary key. */
	includeCtid?: boolean,
	/**  Optimistic-lock guard for editing: any concurrent write bumps xmin. */
	includeXmin?: boolean,
};

/**
 *  The secret (key passphrase or password) rides in on the input but is
 *  stored in the SecretStore, never in the tunnel profile.
 */
export type TunnelInput = {
	name: string,
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
	secret: string | null,
};

export type TunnelProfile = {
	id: string,
	name: string,
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

export type ZsetMember = {
	member: string,
	score: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

