// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => typedError<string, Error>(__TAURI_INVOKE("ping")),
	connectorCapabilities: (kind: ConnectorKind) => typedError<Capability[], Error>(__TAURI_INVOKE("connector_capabilities", { kind })),
	listConnections: () => typedError<ConnectionProfile[], Error>(__TAURI_INVOKE("list_connections")),
	getConnection: (id: string) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("get_connection", { id })),
	createConnection: (input: ConnectionInput) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("create_connection", { input })),
	updateConnection: (id: string, input: ConnectionInput) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("update_connection", { id, input })),
	deleteConnection: (id: string) => typedError<null, Error>(__TAURI_INVOKE("delete_connection", { id })),
	/**  Ephemeral connect + health check; never touches the active connections. */
	testConnection: (input: ConnectionInput, existingId: string | null) => typedError<null, Error>(__TAURI_INVOKE("test_connection", { input, existingId })),
	connect: (id: string) => typedError<null, Error>(__TAURI_INVOKE("connect", { id })),
	disconnect: (id: string) => typedError<null, Error>(__TAURI_INVOKE("disconnect", { id })),
	activeConnections: () => typedError<string[], Error>(__TAURI_INVOKE("active_connections")),
	runQuery: (id: string, sql: string) => typedError<QueryResult, Error>(__TAURI_INVOKE("run_query", { id, sql })),
	cancelQuery: (id: string) => typedError<null, Error>(__TAURI_INVOKE("cancel_query", { id })),
	tableRows: (id: string, request: TableRowsRequest) => typedError<QueryResult, Error>(__TAURI_INVOKE("table_rows", { id, request })),
	streamTableRows: (id: string, request: TableRowsRequest, channel: Channel<RowsChunk>) => typedError<StreamSummary, Error>(__TAURI_INVOKE("stream_table_rows", { id, request, channel })),
	applyTableChanges: (id: string, changes: TableChanges) => typedError<ApplyResult, Error>(__TAURI_INVOKE("apply_table_changes", { id, changes })),
	schemaSnapshot: (id: string) => typedError<SchemaSnapshot, Error>(__TAURI_INVOKE("schema_snapshot", { id })),
	tableDdl: (id: string, schema: string, table: string) => typedError<string, Error>(__TAURI_INVOKE("table_ddl", { id, schema, table })),
	openSqlSession: (connectionId: string) => typedError<string, Error>(__TAURI_INVOKE("open_sql_session", { connectionId })),
	runSessionQuery: (id: string, sql: string) => typedError<QueryResult, Error>(__TAURI_INVOKE("run_session_query", { id, sql })),
	cancelSessionQuery: (id: string) => typedError<null, Error>(__TAURI_INVOKE("cancel_session_query", { id })),
	closeSqlSession: (id: string) => typedError<null, Error>(__TAURI_INVOKE("close_sql_session", { id })),
	listTunnels: () => typedError<TunnelProfile[], Error>(__TAURI_INVOKE("list_tunnels")),
	getTunnel: (id: string) => typedError<TunnelProfile, Error>(__TAURI_INVOKE("get_tunnel", { id })),
	createTunnel: (input: TunnelInput) => typedError<TunnelProfile, Error>(__TAURI_INVOKE("create_tunnel", { input })),
	updateTunnel: (id: string, input: TunnelInput) => typedError<TunnelProfile, Error>(__TAURI_INVOKE("update_tunnel", { id, input })),
	deleteTunnel: (id: string) => typedError<null, Error>(__TAURI_INVOKE("delete_tunnel", { id })),
	/**
	 *  Ephemeral tunnel bring-up: validates the host key and the credentials
	 *  without touching a database (no channel is opened until a client connects).
	 */
	testTunnel: (input: TunnelInput, existingId: string | null) => typedError<null, Error>(__TAURI_INVOKE("test_tunnel", { input, existingId })),
	defaultSshKeys: () => typedError<string[], Error>(__TAURI_INVOKE("default_ssh_keys")),
	trustHostKey: (host: string, port: number, key: string) => typedError<null, Error>(__TAURI_INVOKE("trust_host_key", { host, port, key })),
};

/* Types */
export type ApplyResult = {
	updated: number,
	inserted: number,
	deleted: number,
	durationMs: number | null,
};

export type Capability = "sql-query" | "introspection" | "kv-browse";

export type CellValue = {
	column: string,
	/**  None writes NULL. */
	value: string | null,
};

export type ColumnFilter = {
	column: string,
	op: FilterOp,
	/**  Absent for the null operators. */
	value: string | null,
};

export type ColumnInfo = {
	name: string,
	dataType: string,
	nullable: boolean,
	default: string | null,
};

/**
 *  Coarse type family for UI decisions (alignment, editors, viewers);
 *  `data_type` keeps the exact postgres name.
 */
export type ColumnKind = "bool" | "number" | "text" | "json" | "bytes" | "date-time" | "uuid" | "array" | "other";

/**  Secrets ride in on the input but are stored in the OS keychain, never in the profile. */
export type ConnectionInput = {
	name: string,
	env: Env,
	kind: ConnectorKind,
	host: string,
	port: number,
	database: string,
	user: string,
	sslMode?: SslMode,
	tunnelId?: string | null,
	group?: string | null,
	password: string | null,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	env: Env,
	kind: ConnectorKind,
	host: string,
	port: number,
	database: string,
	user: string,
	sslMode?: SslMode,
	tunnelId?: string | null,
	group?: string | null,
};

export type ConnectorKind = "postgres";

export type Env = "dev" | "staging" | "prod";

/**  Normalized error shape crossing the IPC boundary. */
export type Error = { kind: "not-found"; message: string } | { kind: "storage"; message: string } | { kind: "secret"; message: string } | { kind: "unsupported"; message: string } | { kind: "database"; message: string } | { kind: "tunnel"; message: string } | { kind: "host-key-untrusted"; message: string; host: string; port: number; fingerprint: string; key: string; previouslyTrusted: boolean };

export type FilterOp = "eq" | "neq" | "lt" | "lte" | "gt" | "gte" | "contains" | "starts-with" | "is-null" | "is-not-null";

export type ForeignKeyInfo = {
	name: string,
	columns: string[],
	referencedSchema: string,
	referencedTable: string,
	referencedColumns: string[],
};

export type IndexInfo = {
	name: string,
	definition: string,
	unique: boolean,
};

export type QueryColumn = {
	name: string,
	/**  None when type metadata is unavailable (multi-statement scripts). */
	dataType: string | null,
	kind: ColumnKind,
};

export type QueryResult = {
	statements: StatementResult[],
	notices: ServerNotice[],
	durationMs: number | null,
};

export type RowDelete = {
	key: CellValue[],
};

export type RowInsert = {
	/**  Omitted columns take their DEFAULT. */
	values: CellValue[],
};

export type RowUpdate = {
	key: CellValue[],
	set: CellValue[],
};

export type RowsChunk = {
	/**  Present on the first chunk only. */
	columns: QueryColumn[] | null,
	rows: ((string | null)[])[],
};

export type SchemaInfo = {
	name: string,
	tables: TableInfo[],
};

export type SchemaSnapshot = {
	schemas: SchemaInfo[],
};

export type ServerNotice = {
	severity: string,
	message: string,
};

export type SortDirection = "asc" | "desc";

export type SortSpec = {
	column: string,
	direction: SortDirection,
};

export type SshAuth = { method: "agent" } | { method: "key-file"; path: string } | { method: "password" } | 
/**  No credential: the server authorizes the connection on its own. */
{ method: "none" };

/**
 *  libpq semantics: `require` encrypts without verifying the certificate,
 *  only `verify-full` checks the chain and hostname.
 */
export type SslMode = "disable" | "prefer" | "require" | "verify-full";

export type StatementResult = {
	columns: QueryColumn[],
	rows: ((string | null)[])[],
	rowsAffected: number | null,
};

export type StreamSummary = {
	rows: number | null,
	durationMs: number | null,
	notices: ServerNotice[],
};

export type TableChanges = {
	schema: string,
	table: string,
	updates: RowUpdate[],
	inserts: RowInsert[],
	deletes: RowDelete[],
};

export type TableInfo = {
	name: string,
	kind: TableKind,
	/**  Planner estimate (pg reltuples): -1 when never analyzed. */
	estimatedRows: number | null,
	columns: ColumnInfo[],
	primaryKey: string[],
	indexes: IndexInfo[],
	foreignKeys: ForeignKeyInfo[],
};

export type TableKind = "table" | "view" | "materialized-view";

export type TableRowsRequest = {
	schema: string,
	table: string,
	limit: number,
	offset: number,
	sort: SortSpec | null,
	filters?: ColumnFilter[],
	/**  ctid-keyed editing for tables without a primary key. */
	includeCtid?: boolean,
};

/**
 *  The secret (key passphrase or password) rides in on the input but is
 *  stored in the SecretStore, never in the tunnel profile.
 */
export type TunnelInput = {
	name: string,
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
	secret: string | null,
};

export type TunnelProfile = {
	id: string,
	name: string,
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

