// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => typedError<string, Error>(__TAURI_INVOKE("ping")),
	connectorCapabilities: (kind: ConnectorKind) => typedError<Capability[], Error>(__TAURI_INVOKE("connector_capabilities", { kind })),
	listConnections: () => typedError<ConnectionProfile[], Error>(__TAURI_INVOKE("list_connections")),
	getConnection: (id: string) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("get_connection", { id })),
	createConnection: (input: ConnectionInput) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("create_connection", { input })),
	updateConnection: (id: string, input: ConnectionInput) => typedError<ConnectionProfile, Error>(__TAURI_INVOKE("update_connection", { id, input })),
	deleteConnection: (id: string) => typedError<null, Error>(__TAURI_INVOKE("delete_connection", { id })),
	/**  Ephemeral connect + health check; never touches the active connections. */
	testConnection: (input: ConnectionInput, existingId: string | null) => typedError<null, Error>(__TAURI_INVOKE("test_connection", { input, existingId })),
	connect: (id: string) => typedError<null, Error>(__TAURI_INVOKE("connect", { id })),
	disconnect: (id: string) => typedError<null, Error>(__TAURI_INVOKE("disconnect", { id })),
	activeConnections: () => typedError<string[], Error>(__TAURI_INVOKE("active_connections")),
	runQuery: (id: string, sql: string) => typedError<QueryResult, Error>(__TAURI_INVOKE("run_query", { id, sql })),
	cancelQuery: (id: string) => typedError<null, Error>(__TAURI_INVOKE("cancel_query", { id })),
	tableRows: (id: string, request: TableRowsRequest) => typedError<QueryResult, Error>(__TAURI_INVOKE("table_rows", { id, request })),
	schemaSnapshot: (id: string) => typedError<SchemaSnapshot, Error>(__TAURI_INVOKE("schema_snapshot", { id })),
};

/* Types */
export type Capability = "sql-query" | "introspection" | "kv-browse";

export type ColumnInfo = {
	name: string,
	dataType: string,
	nullable: boolean,
	default: string | null,
};

/**  Secrets ride in on the input but are stored in the OS keychain, never in the profile. */
export type ConnectionInput = {
	name: string,
	env: Env,
	kind: ConnectorKind,
	host: string,
	port: number,
	database: string,
	user: string,
	password: string | null,
};

export type ConnectionProfile = {
	id: string,
	name: string,
	env: Env,
	kind: ConnectorKind,
	host: string,
	port: number,
	database: string,
	user: string,
};

export type ConnectorKind = "postgres";

export type Env = "dev" | "staging" | "prod";

/**  Normalized error shape crossing the IPC boundary. */
export type Error = { kind: "not-found"; message: string } | { kind: "storage"; message: string } | { kind: "secret"; message: string } | { kind: "unsupported"; message: string } | { kind: "database"; message: string };

export type ForeignKeyInfo = {
	name: string,
	columns: string[],
	referencedSchema: string,
	referencedTable: string,
	referencedColumns: string[],
};

export type IndexInfo = {
	name: string,
	definition: string,
	unique: boolean,
};

export type QueryResult = {
	statements: StatementResult[],
	durationMs: number | null,
};

export type SchemaInfo = {
	name: string,
	tables: TableInfo[],
};

export type SchemaSnapshot = {
	schemas: SchemaInfo[],
};

export type SortDirection = "asc" | "desc";

export type SortSpec = {
	column: string,
	direction: SortDirection,
};

export type StatementResult = {
	columns: string[],
	rows: ((string | null)[])[],
	rowsAffected: number | null,
};

export type TableInfo = {
	name: string,
	kind: TableKind,
	/**  Planner estimate (pg reltuples): -1 when never analyzed. */
	estimatedRows: number | null,
	columns: ColumnInfo[],
	primaryKey: string[],
	indexes: IndexInfo[],
	foreignKeys: ForeignKeyInfo[],
};

export type TableKind = "table" | "view" | "materialized-view";

export type TableRowsRequest = {
	schema: string,
	table: string,
	limit: number,
	offset: number,
	sort: SortSpec | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

